### ISSUE TITLE
Should it be replaced with the template introduction description?

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#102]
![Image](https://github.com/6174/comflowyspace/assets/37492595/994c2e30-ff70-46ee-ae5e-9dd6ad37cc2e)

**Comment by 6174** [comment]
Yes, it will be better if we have, you can provide a description column in bitable, I will add then

**Comment by thinkingjimmy** [comment]
I added the bitable. Also add links to workflow tutorials

![Image](https://github.com/6174/comflowyspace/assets/37492595/2a5bd8d1-60b0-4933-b650-1285c57ce8a3)
