### ISSUE TITLE
I've encountered some pytorch bugs, maybe adding some Python related information here would also be meaningful in locating user bugs

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#103]
![Image](https://github.com/6174/comflowyspace/assets/37492595/ffb8d22b-488b-4c6a-8a68-77e5d882d5c3)

**Comment by 6174** [comment]
Python is the same version 3.10.8 in comflowy conda env "await runCommand(`conda create -c anaconda -n ${CONDA_ENV_NAME} python=3.10.8 -y`, dispatcher);"

**Comment by 6174** [comment]
Torch is the latest version: `${PIP_PATH} install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/cpu`;

**Comment by 6174** [comment]
And Looks like your comfyUI version is not show in the UI, This is my situation
![image](https://github.com/6174/comflowyspace/assets/3872872/52ad8f86-e199-4e2e-9678-394c5d797567)
