### ISSUE TITLE
I think the close and its other function buttons could be positioned closer to the image? That way the bottom button won't be obscured either

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#104]
![Image](https://github.com/6174/comflowyspace/assets/37492595/e5c24a45-9e3b-4fd7-b594-7c012264f55c)

**Comment by 6174** [comment]
The Image size is dynamic ,  not stable if close to the image, I can make the close button more clear .

**Comment by 6174** [comment]
And this is a antd image preview module, we can't add too many customization
