### ISSUE TITLE
The image node is not scrollable when there are multiple images（Perhaps look to ComfyUI for optimization）

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#105]
![Image](https://github.com/6174/comflowyspace/assets/37492595/6288e4d1-a0cc-440a-b43c-f4cb6152229a)

**Comment by thinkingjimmy** [comment]
ComfyUI will spread out and then you can click to enlarge. Or we could have a gallery pop up when clicked when there are multiple images?

https://github.com/6174/comflowyspace/assets/37492595/f837a522-2443-487f-b9c1-12383ec2359e

**Comment by 6174** [comment]
Gallery pop up is much better than comfyUI, it's really not stable to create a scroll box in infinite canvas node

**Comment by 6174** [comment]
Marked as closed  considering it's better to optimize gallery UX other than in canvas node  UI
