### ISSUE TITLE
Is it possible for the image viewer to arrange the remaining images below when there are multiple images?

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#106]
![Image](https://github.com/6174/comflowyspace/assets/37492595/35a00fc7-795b-43b1-814b-b689bc2badea)

**Comment by 6174** [comment]
Antd Image preview component support preview group, but not support thumbnails , I will add group first

**Comment by 6174** [comment]
I think we can rewrite the component in the future to add this feature
