### ISSUE TITLE
 ComflowySpace无法在mac x86上运行问题

### ISSUE THREAD

**Issue by KiyoWen** [6174/comflowyspace#126]
ComflowySpace无法在mac x86上运行问题，可有途径解决这问题？
![WechatIMG49300](https://github.com/6174/comflowyspace/assets/156981092/37b97982-b144-43f7-8186-c40327f32481)

**Comment by 6174** [comment]
感谢反馈，应该是需要单独打包支持 x86 版本的包，我们这两天解决一下

**Comment by KiyoWen** [comment]
感谢！我在线等～

**Comment by thinkingjimmy** [comment]
Hello，我们适配了 x86。但需要注意，你的 Macbook 必须是带 AMD 显卡的（这是 pytorch 的要求，暂时没发解决）。如果你的电脑配置 OK，可以下载试用：https://github.com/6174/comflowyspace/releases/tag/v0.0.2-alpha

**Comment by KiyoWen** [comment]
好的
