### ISSUE TITLE
Failed to import image

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#144]
https://github.com/6174/comflowyspace/assets/37492595/aa6d33d1-56fb-477e-9aef-4cc671335eeb

**Comment by thinkingjimmy** [comment]
![Image](https://github.com/6174/comflowyspace/assets/37492595/63119600-6a54-48ea-8ce8-c6877bc723e9)

**Comment by thinkingjimmy** [comment]
After I regenerated a new image, I was able to import it again. Is it because the one that failed was a diagram generated by my previous version?

**Comment by 6174** [comment]
Not a bug, only new version generated image can be imported
