### ISSUE TITLE
Auto-color-changing badcase

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#154]
unCLIP Conditioning change into green, but CLIPText did not change

![Image](https://github.com/6174/comflowyspace/assets/37492595/59f9d8ad-67d6-4442-8165-22ab877f88a6)

**Comment by thinkingjimmy** [comment]
unCLIP model workflow template

**Comment by 6174** [comment]
It's over complicate to calculate cascading condition case, I'll mark won't fix for now
