### ISSUE TITLE
Install onediff node gives error

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#178]
GitHub：https://github.com/siliconflow/onediff/tree/main/onediff_comfy_nodes

![Image](https://github.com/6174/comflowyspace/assets/37492595/1acd9787-9ff9-4d6a-92dc-bba273178af2)

**Comment by thinkingjimmy** [comment]
Re-clicking on the installation shows that the installation was successful：

![Image](https://github.com/6174/comflowyspace/assets/37492595/ac4aa2b5-ec99-45dc-8c3e-18f0066abf1a)

**Comment by thinkingjimmy** [comment]
Still can't get the plugin to work. When I restart the app it gets stuck on startup:

![Image](https://github.com/6174/comflowyspace/assets/37492595/f002815a-8511-42e3-a155-d6df85c75453)

**Comment by 6174** [comment]
There is another problem, if some custom_node raise error, user can't enter app again, and no chance to fix it

**Comment by 6174** [comment]
Added pip install recommendation and pip install entry
