### ISSUE TITLE
IPAdapter extension error

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#201]
Extension: https://github.com/cubiq/ComfyUI_IPAdapter_plus

On the other hand, I can use it on comfyui

![img_v3_028a_8ecf41ab-c39e-4b1a-9621-e5452d9b12eg](https://github.com/6174/comflowyspace/assets/37492595/b9c67eae-fa7b-4fa6-b1fb-19dafc95f46b)

**Comment by 6174** [comment]
Extra info:

1. Install IPAdatper
    - models downloaded from :
        - https://huggingface.co/h94/IP-Adapter/tree/main/models
        - https://huggingface.co/h94/IP-Adapter-FaceID
    - it will show error in Mac M1（Library not loaded: @rpath/libc++.1.dylib），the solution is to execute "conda install libarchive -n comflowy -c conda-forge"
