### ISSUE TITLE
Already have anaconda but comflowyspace still try to install miniconda

### ISSUE THREAD

**Issue by LucasTon53** [6174/comflowyspace#226]
Dear developer,
I met this problem today. I installed all prerequisites before, and then I opened Comflowyspace, trying to import ComfyUI into it. But Comflowyspace cannot detect Anaconda in my system, and still try to install Miniconda in my system, showing the message below. Could you help me figure out the problem? Thanks a lot.

![CleanShot 2024-03-07 at 00 49 37@2x](https://github.com/6174/comflowyspace/assets/25644091/110bb442-e5fa-462a-9b2f-a41f88881ed3)

**Comment by 6174** [comment]
Can you use `conda` command in your terminal, comflowyspace can only find command in the Global PATH ENV
