### ISSUE TITLE
It is recommended to update the action content of the iteration

### ISSUE THREAD

**Issue by bubbl000** [6174/comflowyspace#228]
There is no language switch button, the interface has always been in English and the translation is incomplete, and some plugins are currently invalid. And the operation is not good, every time you create a new component, you need to move the mouse down a distance, which will cause the wrist to be easily fatigued, more difficult to use, according to the comfyui normal right click to create a new component operation will be better, the interface is very beautiful, a code column on the right side is very good, the right code bar can add a new option to check the model lora properties, such as trigger words The source address of the model, the cover of the model 

aigoolike I think I like to be able to preview the cover of the model when selecting a model, but it is also not supported by some plugins, and the appearance is not as good as this project

**Comment by 6174** [comment]
1. Next version will add app settings:
  ![image](https://github.com/6174/comflowyspace/assets/3872872/ea9bb0f1-6b68-4b9c-8f16-fce35b3b55bb)
  
2. "you need to move the mouse down a distance"  seems like it's a bug? I will test it later

3. “check the model lora properties”, do you have any resource to retrieve these properties?  I can see we need a maintained json file to collect these properties

4. Yes, we need maintain our own model properties, and we don't know which model are using (only know the name)

**Comment by bubbl000** [comment]
> 1. Next version will add app settings:下一个版本将添加应用程序设置：
>    ![image](https://private-user-images.githubusercontent.com/3872872/310881313-ea9bb0f1-6b68-4b9c-8f16-fce35b3b55bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NzQ5NDEsIm5iZiI6MTcxMDU3NDY0MSwicGF0aCI6Ii8zODcyODcyLzMxMDg4MTMxMy1lYTliYjBmMS02YjY4LTRiOWMtOGYxNi1mY2UzNWIzYjU1YmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTZUMDczNzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjhlOWU5N2JhZTMyYWVhMDkyZjk4OTljMjcxN2JkYWQ1MTY5ZDk5ZTIwMDk5Y2QzYTkzY2Y1NzdhOTY3YWYyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.T-2UKnntwiFYUGZTSvDz9IfWi2245bsnk01sa8UXduM)
> 2. "you need to move the mouse down a distance"  seems like it's a bug? I will test it later“你需要将鼠标向下移动一段距离”似乎是一个错误？我稍后测试一下
> 3. “check the model lora properties”, do you have any resource to retrieve these properties?  I can see we need a maintained json file to collect these properties“检查模型 lora 属性”，您有任何资源来检索这些属性吗？我可以看到我们需要一个维护的 json 文件来收集这些属性
> 4. Yes, we need maintain our own model properties, and we don't know which model are using (only know the name)是的，我们需要维护自己的模型属性，并且我们不知道正在使用哪个模型（只知道名称）

>2. It’s not a mistake, it’s an operational experience. If my current mouse is in the center of the canvas, and now I want to create a new component, then I need to move the mouse to the option bar below to make a selection. If I do it too many times, my wrist will get tired easily.
>3.What I mean is that a new function has been added that allows users to preview the cover of the currently selected model or the predetermined label attributes when selecting a model or lora.This function can be added to the code bar area on the right

**Comment by thinkingjimmy** [comment]
2. You can quickly evoke the add node menu by double clicking on canvas
3. We'll be supporting lora and checkpoint previews in the future
