### ISSUE TITLE
The responsive of the gallery looks a bit strange

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#23]
the preview button looks strange too:

![Image](https://github.com/6174/comflowyspace/assets/37492595/e07751e6-b8d5-4eb9-8d29-567165053286)

**Comment by 6174** [comment]
How to reproduce this bug?

My case
![image](https://github.com/6174/comflowyspace/assets/3872872/4a5b5ae7-5eda-432e-990a-bc7faed02020)

**Comment by 6174** [comment]
Find it , different image size
