### ISSUE TITLE
macOS，最基本的流程跑不出图

### ISSUE THREAD

**Issue by Luo-hongyi** [6174/comflowyspace#232]
![image](https://github.com/6174/comflowyspace/assets/98020294/16ba794f-fb64-4467-aa9a-22f70d2682d1)

命令行加上参数--force-fp32，解决。希望作者更新

**Comment by benvyeng** [comment]
同macos m2，第一次生图全黑的，重启了一下app，就可以了

**Comment by Luo-hongyi** [comment]
命令行加上参数--force-fp32，解决。希望作者更新

**Comment by thinkingjimmy** [comment]
感谢反馈，我们计划在 v0.1.2 支持

**Comment by thinkingjimmy** [comment]
Hello @Luo-hongyi  可否帮我测试下这个问题是否修复？麻烦安装一下这个安装包：https://www.dropbox.com/scl/fi/a3dny5ivpqwgy1h4od4lc/comflowy-0.1.2-alpha.dmg.zip?rlkey=sdviwbxud9zey87eg0jp1dsct&dl=0

正常启动 Comflowy，然后在 setting 页面，有个 fp 的设置，选 32，然后再打开一个 workflow 出图，看看还会不会出现这种情况？

**Comment by Luo-hongyi** [comment]
@thinkingjimmy 测试过，OK了！

**Comment by catch6** [comment]
不ok啊，还是模糊，FP32 VAE FP32,试了所有组合都不行

**Comment by catch6** [comment]
我提了issue https://github.com/6174/comflowy/issues/63

**Comment by Luo-hongyi** [comment]
RX6600XT只能用Euler sampler，而RX580则fp16 fp32都无问题，应该是显卡问题。
