### ISSUE TITLE
Missing Inputs for efficiency-nodes-comfyui plugin

### ISSUE THREAD

**Issue by TanJeremy** [6174/comflowyspace#240]
Hi, I wanted to try some XY plot with some node from [efficiency-nodes-comfyui](https://github.com/LucianoCirino/efficiency-nodes-comfyui) but the node are missing some input

for exemple:
XY Plot is lacking "dependencies", "X" and "Y" inputs
KSampler (Efficient) nodes are lacking at least "optionnal vae" and "script" inputs

![image](https://github.com/6174/comflowyspace/assets/24638271/69e72c6d-a682-420a-ae07-81ed1acd0bc6)
![image](https://github.com/6174/comflowyspace/assets/24638271/84cbfd13-5f1f-4794-aef2-d0e760180ed7)

**Comment by thinkingjimmy** [comment]
we fixed this bug in v.0.1.3-alpha

give it a try: https://github.com/6174/comflowyspace/releases/tag/v0.1.3-alpha

:)
