### ISSUE TITLE
Feature required : subfolder support 

### ISSUE THREAD

**Issue by CherryGS** [6174/comflowyspace#242]
just identity models in the subfolder 
it's necessery for a big collection

![屏幕截图 2024-03-17 194905](https://github.com/6174/comflowyspace/assets/61844819/fa55915e-0324-40f3-8c6e-090772521d26)

![屏幕截图 2024-03-17 194925](https://github.com/6174/comflowyspace/assets/61844819/0ee852bc-5a31-40e3-98f7-d64f98582389)

![屏幕截图 2024-03-17 195258](https://github.com/6174/comflowyspace/assets/61844819/ff639607-49e9-474a-959e-7afb44cdd1ee)

**Comment by thinkingjimmy** [comment]
Repeated issues: #203
