### ISSUE TITLE
Impossible to work on Complex workflow

### ISSUE THREAD

**Issue by kakachiex2** [6174/comflowyspace#251]
I load one of my Workflow but is a chaos.
- I there a way to bypass group or node...?
- Is there a way to mute group or node...?
- Is reroute supported...?
- I can't find a way to re-organized my workflow not much to do with curve wire = "Chaos spaghetti"
- Curve wire > good for small workflow
- Strait wire > Soft strait wire :: excellent for organization with reroute
- Multi lora stack not supported the node is big
Here is how it looks in ComfyUI and ComflowySpace:: 

ComfyUI :: 

![Screenshot 2024-03-24 000142](https://github.com/6174/comflowyspace/assets/1762112/a1919d6c-cdd5-4641-a387-9794ac68875a)

ComflowySpace :: 

![Screenshot 2024-03-23 234033](https://github.com/6174/comflowyspace/assets/1762112/07269d8c-51f1-49c1-9d64-cf3de4825801)

**Comment by 6174** [comment]
Thanks for the feedback @kakachiex2 ,  most of the issues are known , and these features we are already working:

1.  "strait edge connection " 
2. reroute
3. better group

**Comment by kakachiex2** [comment]
In ComfyUI the first group frame is like index = 0, and all the others group frame created after this one is on top of this first group this is a limitation because the correct way to work is by organizing groups to front, back, backward, forward etc... in this workflow there is no way to organized group or move to front or back, backward etc...
Keep in mind that organization and selection tools is key feature in any tools 3dapp, 2d design app, any app need good organization tools like:: 
- good selection tools
- Align tools > to left, right, top, bottom, center or smart align with smart guides etc...
- send to front, send to back, sent backward for groups frame etc...
- Lock node
- Lock all | unlock all
- Lock | Unlock groups
- Bypass node | group | all | selection
- Mute Node | group | all | selection
- Reroute node support***
- Group frame color is better to change the body too with some transparency this make a really nice appearance and visual and differentiate one to another better.
- Different wire type for me the best one is strait line or strait soft line like ComfyUI Kitchem UI.***
Those are some of the most important function and tools needed for efficient organization of workflow in my experience.

**Comment by kakachiex2** [comment]
> Thanks for the feedback @kakachiex2 , most of the issues are known , and these features we are already working:
> 
> 1. "strait edge connection "
> 2. reroute
> 3. better group
> 
> ![image](https://private-user-images.githubusercontent.com/3872872/316294719-03844614-923d-4876-b7d7-bad70511d6d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyOTMxODgsIm5iZiI6MTcxMTI5Mjg4OCwicGF0aCI6Ii8zODcyODcyLzMxNjI5NDcxOS0wMzg0NDYxNC05MjNkLTQ4NzYtYjdkNy1iYWQ3MDUxMWQ2ZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjRUMTUwODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzZlYmJlZmM3ZWNhY2RjYTllZjU2MjgwYzlmNDg3OTA4ODRhZTJlMDI3YWNiZmJlOGE2Njg5OGJkYzBmZWNmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SEm7lYnRjIErd_XyCIH0VwNVIDIxSCVS1lkWlNab58c)

@6174 Beautifull and thanks for your time to read my post I will give the most of my attention to this project I really like it great work.

**Comment by thinkingjimmy** [comment]
Hi @kakachiex2 , in v0.1.3-alpha:

- Reroute nodes are supported.
- COMBO primitive nodes are supported.
- Disable nodes functionality is supported.
- Added support for straight and polyline connection styles.
- Improved the Group functionality experience.
- Optimized the node UI for more efficient information display.
- Fixed some known compatibility issues and bugs:
  - Fixed the issue of missing plugin nodes.
  - Fixed the misalignment of node values after importing a workflow.
  - Resolved the UI display chaos issue with some plugin nodes.

give it a try: https://github.com/6174/comflowyspace/releases/tag/v0.1.3-alpha

:)
