### ISSUE TITLE
Failed to import workflow

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#26]
https://github.com/6174/comflowyspace/assets/37492595/26e4b3a8-dc79-453e-ae18-14c8b7722862

Import file:
https://comfyanonymous.github.io/ComfyUI_examples/sdturbo/
![Image](https://github.com/6174/comflowyspace/assets/37492595/6c411e94-2009-477b-a88a-046e97e630df)

**Comment by 6174** [comment]
Bug located:

![image](https://github.com/6174/comflowyspace/assets/3872872/66f56727-ed0b-498d-899c-cbf11ee269d2)
