### ISSUE TITLE
模型下载界面跳转下载链接失败

### ISSUE THREAD

**Issue by Cole404** [6174/comflowyspace#262]
虽然也不是啥大问题，Mac客户端内模型界面，就只有麦橘（模型/checkpoint/majic realistic）的模型点击后跳转显示页面失效，其他都正常
<img width="1624" alt="截屏2024-03-31 20 36 13" src="https://github.com/6174/comflowyspace/assets/46254944/78d5cd59-0f58-4524-b77d-3aa0edf3b03b">

**Comment by Cole404** [comment]
正确跳转的地址：https://www.comflowy.com/model/majicMIX-realistic
软件跳转的地址：https://www.comflowy.com/model/majicMix-realistic

**Comment by thinkingjimmy** [comment]
感谢提醒，已修复
