### ISSUE TITLE
进入工作流提示：App init failed: Unexpected token 'E', "Error occu"... is not valid JSON

### ISSUE THREAD

**Issue by jakqwe** [6174/comflowyspace#268]
进入工作流提示：App init failed: Unexpected token 'E', "Error occu"... is not valid JSON，该怎么解决

**Comment by thinkingjimmy** [comment]
这个应该在新版已经修复，你是用什么版本的呢？另外，你需要点击右上角的 terminal 看看是什么报错，如果是 stop server ，则点击下重启服务。

**Comment by jakqwe** [comment]
感谢，看了 terminal 显示显卡驱动太旧了，更新完就好了
