### ISSUE TITLE
Ksampler custom node is missing the "add_noise" setting

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#27]
![Image](https://github.com/6174/comflowyspace/assets/37492595/5f795ccc-6503-47c0-9bdb-bc645179460c)

**Comment by 6174** [comment]
Add_noise is not  in Ksampler widget, what's does this filed do?

![Image](https://github.com/6174/comflowyspace/assets/3872872/4d59623f-0628-48b8-a1c3-45e072564c47)

**Comment by 6174** [comment]
My fault， find the field definition



![Image](https://github.com/6174/comflowyspace/assets/3872872/eff55c18-013d-44a6-be5c-59a8025fff61)

**Comment by 6174** [comment]
https://github.com/6174/comflowyspace/pull/33/files
