### ISSUE TITLE
我在手动安装efficiency-nodes-comfyui和ComfyUI-Inference-Core-Nodes后再次启动comflowy时出现错误，在多次重装和重启后仍然没有解决

### ISSUE THREAD

**Issue by xiaosen3333** [6174/comflowyspace#270]
![image](https://github.com/6174/comflowyspace/assets/114582142/8d434ecc-6863-4f69-9aa2-7219c21e7724)
Start ComfyUI failed
Start Session Failed:File not found: Error: File not found: at new WindowsPtyAgent (D:\comflowy\resources\app.asar\node_modules\node-pty\lib\windowsPtyAgent.js:83:36) at new WindowsTerminal (D:\comflowy\resources\app.asar\node_modules\node-pty\lib\windowsTerminal.js:51:24) at Object.spawn (D:\comflowy\resources\app.asar\node_modules\node-pty\lib\index.js:29:12) at ComfyuiService.startTerminal (D:\comflowy\resources\app.asar\layers\main\dist\index.js:115050:27) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async ComfyuiService.startComfyUI (D:\comflowy\resources\app.asar\layers\main\dist\index.js:115126:7) at async executor (D:\comflowy\resources\app.asar\layers\main\dist\index.js:131310:26) at async processJob (D:\comflowy\resources\app.asar\layers\main\dist\index.js:115667:22)

**Comment by thinkingjimmy** [comment]
efficiency 插件更新了，需要更新 ComfyUI 才能顺利安装。你可以手动渠道插件页面，删除掉 efficacy 插件，然后更新ComfyUI 后再安装 efficiency 插件

**Comment by xiaosen3333** [comment]
谢谢，我试试

**Comment by thinkingjimmy** [comment]
新版本好了吗？
