### ISSUE TITLE
Where are workflows saved?

### ISSUE THREAD

**Issue by jffaust** [6174/comflowyspace#271]
Relevant documentation: https://www.comflowy.com/blog/comflowy-vs-comfyui#-supports-workflow-management-functions

_"The second major distinguishing feature of ComflowySpace is the addition of Workflow management functions. This feature allows you to manage your Workflow more conveniently, and every change you make will be automatically saved,"_

Where are they saved? I looked around the files of the installation destination and I could not see my workflows.

My initial thought when I saw this automatic workflow management was that I could arrange workflows as files in a folder hierarchy and configure the save location so that it is a git repo so I can backup and control versions of my workflows.

Is this not possible?

**Comment by Nick22nd** [comment]
Derived from `path.join(os.homedir(), 'comflowy')`, the typical paths are:

• On Mac: ~/comflowy/db/workflows
• On Windows: c:\users\your_username\comflowy\db\workflows

**Comment by jffaust** [comment]
Found it at the path described above on Windows.
![image](https://github.com/6174/comflowyspace/assets/4367222/cfff8f8c-3679-4fbc-be04-de5e586cab5b)

Looks like file names for the workflows are GUIDs so might not be that usable as a git repo.

**Comment by jffaust** [comment]
Found it at the path described above on Windows.
![image](https://github.com/6174/comflowyspace/assets/4367222/cfff8f8c-3679-4fbc-be04-de5e586cab5b)

Looks like file names for the workflows are GUIDs so might not be that usable as a git repo.

**Comment by jffaust** [comment]
Found it at the path described above on Windows.
![image](https://github.com/6174/comflowyspace/assets/4367222/cfff8f8c-3679-4fbc-be04-de5e586cab5b)

Looks like file names for the workflows are GUIDs so might not be that usable as a git repo.
