### ISSUE TITLE
image loading node cannot be automatically adjusted

### ISSUE THREAD

**Issue by BailinSong** [6174/comflowyspace#276]
![image](https://github.com/6174/comflowyspace/assets/2916937/ef800481-e421-4e55-bc15-2a9adf020a26)

The picture in the image loading node cannot be automatically adjusted with the node size.

**Comment by thinkingjimmy** [comment]
This is a bug, we will fix it in the next version.

**Comment by thinkingjimmy** [comment]
fixed
