### ISSUE TITLE
一直报错，不知道怎么解决，求教！

### ISSUE THREAD

**Issue by binfei110** [6174/comflowyspace#280]
终端提示：
got prompt
Failed to validate prompt for output 9:
* EmptyLatentImage 5:
  - Required input is missing: batch_size
* KSampler 3:
  - Required input is missing: steps
  - Required input is missing: cfg
  - Required input is missing: denoise
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

运行结果：
<img width="549" alt="image" src="https://github.com/6174/comflowyspace/assets/54383548/329952bb-437d-4acc-8b57-54ea26f68b8f">

通知栏报错
<img width="397" alt="image" src="https://github.com/6174/comflowyspace/assets/54383548/b7ae73cf-69a0-414d-bd13-8816e4c74725">

**Comment by thinkingjimmy** [comment]
你使用默认的 workflow 运行也会这样吗？

**Comment by binfei110** [comment]
> 你使用默认的 workflow 运行也会这样吗？

用的就是默认的flow。不过解决了，就是把报错中提到的错误的参数都重新设置一下。应该是之前第一次设置没有传到下一个节点。但不知道为啥会这样。
