### ISSUE TITLE
在流程里面，有一些面板缺失内容，比如文字显示框

### ISSUE THREAD

**Issue by jememouse** [6174/comflowyspace#285]
在流程里面，有一些面板缺失内容，比如文字显示框
但是在comfyui里面，又是有内容的。
![SCR-20240429-eyvj](https://github.com/6174/comflowyspace/assets/9528120/92fafee8-a223-4e4b-9213-02a1ed76a396)
![SCR-20240429-eyha](https://github.com/6174/comflowyspace/assets/9528120/1fb6af27-abfe-495d-9673-05fc00617e28)

**Comment by myface-wang** [comment]
是的，wd14的文本显示框，也是无法正常显示的

**Comment by thinkingjimmy** [comment]
我们会逐步支持。感谢反馈。
