### ISSUE TITLE
安装Comflowy时失败

### ISSUE THREAD

**Issue by SJcscl** [6174/comflowyspace#290]
在安装
![Uploading image.png…]()
时

<img width="539" alt="ed7e1803806bc6e9ba1a4d3caac3238" src="https://github.com/6174/comflowyspace/assets/169170263/7e7974d9-b71c-4245-b27e-0f028b095fa1">
卡在了这一个步骤
随后出现了以下错误提示
<img width="420" alt="0e4ad7b40942d60602bf4021bebb4f0" src="https://github.com/6174/comflowyspace/assets/169170263/3587a12e-d704-4116-a4ef-dc23a610a4a6">

请求帮助！

**Comment by xuchuang12** [comment]
我也遇到了，安装失败。

**Comment by xuchuang12** [comment]
你可以尝试右键以管理员身份运行，我无意中安装成功了，之前也是一直报错。

**Comment by thinkingjimmy** [comment]
如果是卡在 downloading，那可能是网络的问题，你可以尝试自己手动下载。如果是 win 电脑最好是管理员身份运行。
