### ISSUE TITLE
Python目录能自己指定吗?

### ISSUE THREAD

**Issue by cunkai** [6174/comflowyspace#296]
我Intel显卡 现在comflowyspace自己配置的python无法运行

**Comment by cunkai** [comment]
另外ComfyUI官方是有Intel单独的requirements-ipex.txt

在 ComfyUI\user 目录下

**Comment by thinkingjimmy** [comment]
我们尝试过增加此 ipex 但发现无法运行，就回退了。暂时因为缺少测试机器无法支持。抱歉。或许等有没有好心的开发者帮忙支持下。
