### ISSUE TITLE
Ambiguity in the name and the problem with button layout

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#55]
I think load default is better.

![Image](https://github.com/6174/comflowyspace/assets/37492595/44267531-22ec-4f11-9870-bff3471f259a)

**Comment by thinkingjimmy** [comment]
On the other hand, I don't think this page needs to provide "Reset Workflow" feature. I will prefer user add a new workflow. 

ComfyUI need this button because it does not have the workspace feature, so user must use the Rest Workflow button to add a new workflow.

**Comment by 6174** [comment]
Fixed
