### ISSUE TITLE
I think image node would be better to add scrollbars, and also to add more columns

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#56]
![Image](https://github.com/6174/comflowyspace/assets/37492595/76242a21-a85d-4cb8-9fce-80dad6021579)

**Comment by 6174** [comment]
Add a simple grid view style if there is multiple images, since there is a preview action vs ComfyUI, no need to directly render large size image.  (Plus there are many badcases when resize the node)
