### ISSUE TITLE
After loading the workflow, the node's UI style will be messed up

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#59]
https://github.com/6174/comflowyspace/assets/37492595/bd9a250c-e663-4d13-8992-8668372268ba

**Comment by thinkingjimmy** [comment]
On the other hand, I don't think this page needs to provide "Load Workflow" feature. I will prefer user add a new workflow by importing.

**Comment by 6174** [comment]
Bugfix https://github.com/6174/comflowyspace/commit/db7bc8474436be6f947e6debad53854f20f27129

I think the button is needed, It's other kind of reset, but reset from user, it's like figma or photoshop  import feature
