### ISSUE TITLE
Nothing is loaded in the product window, but it can be loaded through the browser

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#71]
![Image](https://github.com/6174/comflowyspace/assets/37492595/c89515e8-2a22-474f-ae21-99aeb2697862)

**Comment by thinkingjimmy** [comment]
I suspect it's because of this:


![Image](https://github.com/6174/comflowyspace/assets/37492595/8c9bbc68-ca5f-44e2-b94d-7b1d8d6eb8ae)

**Comment by 6174** [comment]
Not a bug, it's a development issue, you need to start frontend project then start electron , otherwise electron can't load ui
