### ISSUE TITLE
When importing ComfyUI workflow, the Image node is not recommended to load the file (because there is a high probability that the file will not be available locally)

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#74]
![Image](https://github.com/6174/comflowyspace/assets/37492595/21c9f75d-cb31-411b-b35f-9cdb42fcc14a)

**Comment by 6174** [comment]
Add static error check to notify user after the workflow is loaded

![Image](https://github.com/6174/comflowyspace/assets/3872872/7c45e309-32d2-446b-bc55-1a6dbfcea5f0)
