### ISSUE TITLE
Not sure if the dev environment is causing the problem, the download folder is a hidden folder

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#84]
![Image](https://github.com/6174/comflowyspace/assets/37492595/f5f3f7c8-5a6a-4c89-94b1-19662162b8f4)

**Comment by thinkingjimmy** [comment]
I used another laptop, have the same problem:

![Image](https://github.com/6174/comflowyspace/assets/37492595/f5256797-e338-4b15-969e-e5cb97d4e3cc)

**Comment by 6174** [comment]
I test on my computer, it's the default download path, I think maybe your computer settings sync across devices and the default download path is the hidden
