### ISSUE TITLE
When I click on the connection point, the dot of the connectable point gets bigger, but the bigger is not from the center of the circle

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#88]
https://github.com/6174/comflowyspace/assets/37492595/293166b8-66ed-4bdc-9afb-142e34467be1

**Comment by 6174** [comment]
I change the default behavior, but it's still not in the center, and it is not just a css issue, it will effect node auto adjust height algorithm , I will optimize it in the future.
