### ISSUE TITLE
The search doesn't have to be an exact match, it should be possible to search for results without entering spaces

### ISSUE THREAD

**Issue by thinkingjimmy** [6174/comflowyspace#96]
![Image](https://github.com/6174/comflowyspace/assets/37492595/16818693-d89c-4c2a-a276-93bb2fc8a466)

![Image](https://github.com/6174/comflowyspace/assets/37492595/15c93d11-7b87-46de-b142-03cdea0e850a)

**Comment by 6174** [comment]
Add a maxString match length test algorithm and simple word split, it will be better now
